# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rubanketb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rubanketb
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Fabric'
  pod 'Crashlytics'

  #pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'
  pod 'AppsFlyerFramework'

end
