# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rubanketb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'AppsFlyerFramework'

  # Pods for rubanketb

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'rubanketbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
