# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rubanketb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  pod 'React', :path => '../node_modules/react-native'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'AppsFlyerFramework'

  # Pods for rubanketb

  #pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  target 'rubanketbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
